# Site settings

# for production:
# baseurl = "http://www.caseymetz.tech/"

# for development:
baseurl = "/"

languageCode = "en-us"
title = "Casey Metz"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-96527389-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Casey Thomas Metz"
  description = "My software engineer frontend web development portfolio site, featuring javascript, react, redux, sass, es6, node, and jquery."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "img/favicon.ico"
  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    logo = "bonsai-svg-white.svg"
    about = "About"
    tech = "Tech"
    portfolio = "Portfolio"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://gohugo.io"
      name = "External link"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Casey Metz"
    subtitle = "Software Engineering, Development, & Design"

  # about section
  [params.about]
    enable = true
    title = "About"

    [[params.about.row]]

    [[params.about.row.list]]
      icon = "fa-gears"
      title = "Useful"
      description = "Knowing how to code is like having magical powers: I can see a need and pull a thing out of nothingness to meet that need. I feel most fulfilled when I use these powers to build technology that helps people, making their lives easier."

    [[params.about.row.list]]
      icon = "fa-mobile-phone"
      title = "Responsive"
      description = "Responsiveness means more than just screen-sizes; it functioning seemlessly across browsers and operating systems as well. No one wants to be trapped in front of a desktop machine all day. (Actually, some of us don't mind it so much...)"

    [[params.about.row.list]]
      icon = "fa-users"
      title = "Accesible"
      description = "Accomodating people with different abilities is not an extra feature, it is a fundamental responsibility. For many, an inaccesible site is a broken site. Developers must build accesible products if the internet is to live up to its democratizing potential."

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = "Here are some examples of things I've built in the past, works-in-progress, and ideas for future projects."

    [params.portfolio.modal]
      deployed = "Deployed"
      code = "Code"
      category = "category"
      buttonText = "Close project"


    # About section
  [params.tech]
    enable = true
    title = "Tech"
    subtitle = "These are some of the technologies I've used either personally or professionally. I love learning new tech as well! This list just represents the flavor of the stacks with which I'm most familiar."

  # Contact section
  [params.contact]
    enable = true
    title = "Contact me"
    subtitle  = "I'm open to new projects and connections, or just chatting tech!"
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "caseymetz@gmail.com"

    # Success and error message overwrite for async contact form
    thanks = "Thank you for contacting me, I'll be sure to get in touch soon!"
    error = "Message could not be send. Please contact me at caseymetz@gmail.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true

    [[params.footer.resume]]
      title="Résumé"
      icon = "fa-file-pdf-o"
      link = "img/Resume.pdf"

    [[params.footer.social]]
      title="Twitter"
      icon = "fa-twitter"
      link = "https://twitter.com/CaseyTMetz"

    [[params.footer.social]]
      title="GitHub"
      icon = "fa-github"
      link = "https://github.com/Casey1449"

    [[params.footer.social]]
      title="Linkedin"
      icon = "fa-linkedin"
      link = "https://www.linkedin.com/in/casey-metz-732804132"
